version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/rust:latest-node
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            #sudo apt-get install -y lldb
            ulimit -c unlimited
            cargo test -v || true;
            ls ./target/debug/deps/parinfer_rust-*
            for f in ./target/debug/deps/parinfer_rust-*; do
              RUST_STACKTRACE=1 "$f"
              break
            done
      - run:
          name: Saving core dumps
          command: |
            mkdir -p /tmp/core_dumps
            find target -name 'core.*' -exec cp {} /tmp/core_dumps/ \;
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
